### PR TITLE
add nip14, reputation scheme.

### PR DESCRIPTION
**Pull request by fiatjaf**
I've had these ideas in my mind for a long time.
I need feedback before I try to implement them.

closes https://github.com/fiatjaf/nostr/issues/20.

### CODE REVIEW

**Comment by scsibug** [comment]
How would one represent negative sentiment?  Presumably a rating of zero represents "no knowledge" of the category being evaluated.  How can I express that someone is "maximally dishonest"?

**Comment by fiatjaf** [comment]
Shouldn't zero should represent negative sentiments, and no knowledge should be just not having anything mentioned?

But indeed you pose a good question.

Because we also have to deal with repeated events for the same target. If A publishes `bob is honest: 44` but later publishes `bob is honest: 77` it is clear how to interpret, but if the second event is just `bob is dentist: 55` then we don't know if Bob's honesty evaluation changed for Alice or not.

**Comment by vinliao** [comment]
This reputation-based is actually a replacement for the follow-based system: instead of displaying how much people follow you, you can display what people think of you. The "following" and "follower" numbers are one-dimensional; reputation given by others is more nuanced, has more weight.

Not all ratings are created equal, though. The reputation `honest: 90` and `coder: 95`, given by Elon (for instance), has more weight than the same reputation given by a rando. From my shallow skimming of the NIP, I don't think it covers this aspect.

(There's a typo on the title: it says "NIP-07" instead of "NIP-14".)

**Comment by etemiz** [comment]
This is probably the most important NIP.

I have nothing to add to this NIP (for now).

However I feel like the nature of nostr is very open to floods or abuse. I propose hashcash or proof of humanity for spammy behaviour (when the relay sees a spammy behavior it starts asking harder hashcash or more frequent proof of humanity).

**Comment by acailly** [comment]
(Random thoughts)
I wonder if this could be the foundation to implement something like TrustNet (https://cblgh.org/trustnet/)
Rating types in the NIP seems to be equivalent to Trust Areas
The proposed algorithm takes trust statements for "3-6 nodes away from the root", could have a huge impact on relay bandwidth

**Comment by Giszmo** [comment]
nips moved to https://github.com/nostr-protocol/nips
We should close this and all other nip PRs.

This looks like it should be linked to

* https://github.com/nostr-protocol/nips/pull/46

**Pull request closed without merging**
