### PR TITLE
updated to proper naming convention: nostr to the nostr

### PR DESCRIPTION
**Pull request by derekross**
nevent1qqsy96sghxka05epdhvmj5v6z6crkfyw6vgt7qxspxmezkawmkl5wcqpz9mhxue69uhkummnw3ezuamfdejj7q3q80cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsxpqqqqqqz22z6fl

### CODE REVIEW

**Review by Cameri — APPROVED** [review]
This is crazy! Approved.

**Comment by pablof7z** [comment]
hahahahhahahahaaa

**Comment by ralyodio** [comment]
this is the dumb

**Comment by matata2140** [comment]
#171 it's time 👀
@Cameri
@fiatjaf

**Comment by matata2140** [comment]
> #171 it's time 👀 @Cameri @fiatjaf

pls ser mi familia

**Comment by CarlosPinheiro1986** [comment]
hondadopoder09@zbd.gg

**Pull request merged**
