### PR TITLE
NIP-15 relating events to resources

### PR DESCRIPTION
**Pull request by Cameri**

### CODE REVIEW

**Comment by fiatjaf** [comment]
This looks very good, I'm impressed by the collection of examples.

One question I have is: how are we going to know the schema for each of these types of witness events? For example, how do I know if I should check for the JSON field "star" or the JSON field "redirect" and so on?

 I think maybe this NIP should host all the canonical formats for all these types of witnesses (and we can add more later as they appear).

I was also thinking that instead of a single "witness" kind it would be simpler and cleaner to have a different kind for each -- and no need for multiple NIPs. all these kinds could be defined in this same NIP.

For example:
- kind 10: website star, expects the URI tag and blank content
- kind 11: spam phone number, expects the tel tag and blank content
-

**Comment by fiatjaf** [comment]
> A Browser extension that uses Nostr may request a relay for comments for a website the user is browsing.

Now about this I'm confused. because I was thinkingabout making such an extension, but it would use kind1 notes with an extra URL tag.

Do you think it is better to have a separate kind for these? Comments are essentially text notes, I think, and it would be nice if they showed up on a client like branle so other people could jump into the discussion.

Simultaneously, reddit-like clients that do dedicated commenting about URLs would also use kind1 and everything would be mixed, which is good, I think.

What do you think?

**Comment by fiatjaf** [comment]
So you think the current kind system is already overblown? Why shouldn't we just remove the `kind` altogether and replace it with a `$schema` field that points to an URL that describes that schema?

**Comment by melvincarvalho** [comment]
Some food for thought, some stuff may be able to be resused e.g. (names, structure etc.)

I'm not sure how well that JSON will fit with this, but it is widely deployed 

https://schema.org/Rating

**Comment by fiatjaf** [comment]
I have the impression that some of these things are duplicated. For example, to "like strongly" isn't similar to give a rate of 100, and to "like slightly" to give a 75? What about "star", that gotta be similar to "like", right?

**Comment by fiatjaf** [comment]
Why? What is the difference?

**Comment by Cameri** [comment]
Rating here collides with NIP-14 and here it's just a poorer definition. Will remove.

**Comment by HamishMacEwan** [comment]
> Why? What is the difference?

The former attempts futilely to anticipate all possible **kinds**, the latter is light-weight and extensible by coöperating clients.

The former requires 100s of implementations of **kinds** depending on `MUST`, `SHOULD`, `MAY` while the latter means only those clients that value the functionality will seek it out or implement it.

The loss of homogeneity is compensated for by saving the conformity cost and providing flexibility and choice for private ordering among clients.

It also provides a differentiation among clients, what they support or don't.  I run a branle instance so I can change the 240 character limit.

As always

```
this is why a heavy-duty core will always lose...by definition, it must offer services which are of interest to only a subset of its users and yet all users are impacted by them...

/mtr
```

**Comment by fiatjaf** [comment]
Kinds are not expected to be homogenous, they're not mandatory, they're not attempting to anticipate everything, they're just soft descriptions of possibilities. Clients can implement some kinds and not some other kinds.

It's basically the same thing, but without injecting some arbitrary dependency on some random URL and instead aggregating all specs in a single place, which is the NIPs repository.

URLs don't have magic powers, URLs are just like NIPs, and people will still have to agree with each other, URLs don't solve that.

**Comment by Cameri** [comment]
Will be revamping this NIP. Only the `r` tag is useful here and new kinds are not needed at all.

**Pull request closed without merging**
